#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Starting installation in user home directory ($HOME)..."

ln -sn $BASEDIR/.vim ~/.vim
ln -sn $BASEDIR/.vimrc ~/.vimrc
ln -sn $BASEDIR/.i3 ~/.i3
ln -sn $BASEDIR/.gitconfig ~/.gitconfig

# Initialize vim settings
[ ! -d "$BASEDIR/.vim/bundle/Vundle.vim" ] && \
  mkdir -p $BASEDIR/.vim/bundle
  git clone https://github.com/VundleVim/Vundle.vim.git $BASEDIR/.vim/bundle/Vundle.vim && \
  vim +PluginInstall +qall 

echo "Everything installed... Bye!"
